import type { PythonFunction, TrainerQuestion } from "./types";
import { generateExample } from "./example-generators";
import { pickRandom } from "./utils";

export const pythonFunctions: PythonFunction[] = [
  {
    slug: "len",
    name: "len()",
    category: "Функциональные инструменты",
    shortDescription: "Возвращает количество элементов в объекте.",
    fullDescription: "Функция len() — одна из самых часто используемых в Python. Она подсчитывает длину строки, количество элементов в списке или пар в словаре.",
    defaultCode: 'text = "Python"\nresult = len(text)',
    defaultInput: '"Python"',
    defaultOutput: "6",
    defaultSteps: [
      { title: "Вызов len()", description: "Передаём объект в функцию len()." },
      { title: "Подсчёт", description: "Функция считает количество элементов." },
    ],
    defaultVisualization: { before: ["Python"], after: ["6"], type: "simple" },
    applications: ["Проверка длины пароля", "Подсчёт элементов в списке", "Валидация данных"],
    sampleInput: '"hello"',
    sampleOutput: "5",
  },
  {
    slug: "str-upper",
    name: "str.upper()",
    category: "Строки",
    shortDescription: "Переводит все символы строки в верхний регистр.",
    fullDescription: "Метод upper() создаёт новую строку, где каждая буква написана заглавными. Числа и знаки не меняются.",
    defaultCode: 'text = "hello"\nresult = text.upper()',
    defaultInput: '"hello"',
    defaultOutput: '"HELLO"',
    defaultSteps: [
      { title: "Метод upper()", description: "Вызываем text.upper() на строке." },
      { title: "Результат", description: "Все буквы становятся заглавными." },
    ],
    defaultVisualization: { before: ["hello"], after: ["HELLO"], type: "simple" },
    applications: ["Форматирование текста", "Сравнение без учёта регистра", "Заголовки"],
    sampleInput: '"python"',
    sampleOutput: '"PYTHON"',
  },
  {
    slug: "str-lower",
    name: "str.lower()",
    category: "Строки",
    shortDescription: "Переводит все символы строки в нижний регистр.",
    fullDescription: "Метод lower() возвращает копию строки, где все буквы строчные. Полезен для нормализации ввода пользователя.",
    defaultCode: 'text = "PYTHON"\nresult = text.lower()',
    defaultInput: '"PYTHON"',
    defaultOutput: '"python"',
    defaultSteps: [
      { title: "Метод lower()", description: "Вызываем text.lower()." },
      { title: "Результат", description: "Все буквы становятся строчными." },
    ],
    defaultVisualization: { before: ["PYTHON"], after: ["python"], type: "simple" },
    applications: ["Нормализация email", "Поиск без регистра", "Обработка команд"],
    sampleInput: '"Hello"',
    sampleOutput: '"hello"',
  },
  {
    slug: "str-split",
    name: "str.split()",
    category: "Строки",
    shortDescription: "Разбивает строку на список по разделителю.",
    fullDescription: "Метод split() разделяет строку на части и возвращает список. По умолчанию разделитель — пробел.",
    defaultCode: 'text = "red blue green"\nresult = text.split()',
    defaultInput: '"red blue green"',
    defaultOutput: '["red", "blue", "green"]',
    defaultSteps: [
      { title: "Метод split()", description: "Строка разбивается по пробелам." },
      { title: "Результат", description: "Получается список из трёх слов." },
    ],
    defaultVisualization: { before: ["red blue green"], after: ["red", "blue", "green"], type: "string-split" },
    applications: ["Разбор CSV-данных", "Обработка команд", "Токенизация текста"],
    sampleInput: '"a,b,c"',
    sampleOutput: '["a", "b", "c"]',
  },
  {
    slug: "str-replace",
    name: "str.replace()",
    category: "Строки",
    shortDescription: "Заменяет одну подстроку на другую.",
    fullDescription: "Метод replace(old, new) находит все вхождения old и заменяет их на new. Возвращает новую строку.",
    defaultCode: 'text = "I like cats"\nresult = text.replace("cats", "dogs")',
    defaultInput: '"I like cats"',
    defaultOutput: '"I like dogs"',
    defaultSteps: [
      { title: "Метод replace()", description: 'Заменяем "cats" на "dogs".' },
      { title: "Результат", description: "Создаётся новая строка с заменой." },
    ],
    defaultVisualization: { before: ["I like cats"], after: ["I like dogs"], type: "simple" },
    applications: ["Цензура текста", "Форматирование", "Исправление опечаток"],
    sampleInput: '"hello world"',
    sampleOutput: '"hello Python"',
  },
  {
    slug: "str-strip",
    name: "str.strip()",
    category: "Строки",
    shortDescription: "Удаляет пробелы в начале и конце строки.",
    fullDescription: "Метод strip() убирает лишние пробельные символы с краёв строки. Часто используется при обработке ввода.",
    defaultCode: 'text = "  hello  "\nresult = text.strip()',
    defaultInput: '"  hello  "',
    defaultOutput: '"hello"',
    defaultSteps: [
      { title: "Метод strip()", description: "Удаляем пробелы с обоих концов." },
      { title: "Результат", description: 'Остаётся чистая строка "hello".' },
    ],
    defaultVisualization: { before: ["  hello  "], after: ["hello"], type: "simple" },
    applications: ["Очистка ввода пользователя", "Парсинг файлов", "Валидация форм"],
    sampleInput: '"  data  "',
    sampleOutput: '"data"',
  },
  {
    slug: "str-find",
    name: "str.find()",
    category: "Строки",
    shortDescription: "Ищет подстроку и возвращает её индекс.",
    fullDescription: "Метод find(sub) возвращает позицию первого вхождения подстроки. Если не найдено — возвращает -1.",
    defaultCode: 'text = "hello world"\nresult = text.find("world")',
    defaultInput: '"hello world"',
    defaultOutput: "6",
    defaultSteps: [
      { title: "Метод find()", description: 'Ищем "world" в строке.' },
      { title: "Результат", description: "Подстрока начинается с индекса 6." },
    ],
    defaultVisualization: { before: ["hello world"], after: ["6"], type: "simple" },
    applications: ["Поиск в тексте", "Парсинг URL", "Анализ логов"],
    sampleInput: '"python code"',
    sampleOutput: "0",
  },
  {
    slug: "list-append",
    name: "list.append()",
    category: "Списки",
    shortDescription: "Добавляет элемент в конец списка.",
    fullDescription: "Метод append(x) изменяет список на месте, добавляя элемент x в конец. Возвращает None.",
    defaultCode: "numbers = [1, 2, 3]\nnumbers.append(4)",
    defaultInput: "[1, 2, 3]",
    defaultOutput: "[1, 2, 3, 4]",
    defaultSteps: [
      { title: "Метод append()", description: "Добавляем 4 в конец списка." },
      { title: "Результат", description: "Список увеличился на один элемент." },
    ],
    defaultVisualization: { before: ["1", "2", "3"], after: ["1", "2", "3", "4"], type: "list-transform" },
    applications: ["Накопление данных", "Построение списков", "Очереди"],
    sampleInput: "[10, 20]",
    sampleOutput: "[10, 20, 30]",
  },
  {
    slug: "list-pop",
    name: "list.pop()",
    category: "Списки",
    shortDescription: "Удаляет и возвращает последний элемент.",
    fullDescription: "Метод pop() удаляет элемент с конца списка и возвращает его. Можно указать индекс.",
    defaultCode: "numbers = [1, 2, 3, 4]\nremoved = numbers.pop()",
    defaultInput: "[1, 2, 3, 4]",
    defaultOutput: "4",
    defaultSteps: [
      { title: "Метод pop()", description: "Удаляем последний элемент." },
      { title: "Результат", description: "Возвращается 4, список стал [1, 2, 3]." },
    ],
    defaultVisualization: { before: ["1", "2", "3", "4"], after: ["1", "2", "3"], type: "list-transform" },
    applications: ["Стек (LIFO)", "Отмена последнего действия", "Обработка очереди"],
    sampleInput: "[5, 10, 15]",
    sampleOutput: "15",
  },
  {
    slug: "list-remove",
    name: "list.remove()",
    category: "Списки",
    shortDescription: "Удаляет первое вхождение значения.",
    fullDescription: "Метод remove(x) находит первый элемент со значением x и удаляет его из списка.",
    defaultCode: "numbers = [1, 2, 3, 2]\nnumbers.remove(2)",
    defaultInput: "[1, 2, 3, 2]",
    defaultOutput: "[1, 3, 2]",
    defaultSteps: [
      { title: "Метод remove()", description: "Удаляем первое вхождение 2." },
      { title: "Результат", description: "Список: [1, 3, 2]." },
    ],
    defaultVisualization: { before: ["1", "2", "3", "2"], after: ["1", "3", "2"], type: "list-transform" },
    applications: ["Удаление дубликатов", "Фильтрация данных", "Очистка списков"],
    sampleInput: "[10, 20, 30]",
    sampleOutput: "[10, 30]",
  },
  {
    slug: "list-sort",
    name: "list.sort()",
    category: "Списки",
    shortDescription: "Сортирует список на месте.",
    fullDescription: "Метод sort() упорядочивает элементы списка по возрастанию (или по ключу). Изменяет исходный список.",
    defaultCode: "numbers = [3, 1, 4, 1, 5]\nnumbers.sort()",
    defaultInput: "[3, 1, 4, 1, 5]",
    defaultOutput: "[1, 1, 3, 4, 5]",
    defaultSteps: [
      { title: "Метод sort()", description: "Сортируем элементы по возрастанию." },
      { title: "Результат", description: "Список упорядочен: [1, 1, 3, 4, 5]." },
    ],
    defaultVisualization: { before: ["3", "1", "4", "1", "5"], after: ["1", "1", "3", "4", "5"], type: "list-transform" },
    applications: ["Рейтинги", "Сортировка данных", "Подготовка к анализу"],
    sampleInput: "[5, 2, 8]",
    sampleOutput: "[2, 5, 8]",
  },
  {
    slug: "sorted",
    name: "sorted()",
    category: "Списки",
    shortDescription: "Возвращает новый отсортированный список.",
    fullDescription: "Функция sorted() создаёт новый список с отсортированными элементами, не изменяя исходный.",
    defaultCode: "numbers = [3, 1, 4]\nresult = sorted(numbers)",
    defaultInput: "[3, 1, 4]",
    defaultOutput: "[1, 3, 4]",
    defaultSteps: [
      { title: "Функция sorted()", description: "Создаём отсортированную копию." },
      { title: "Результат", description: "Исходный список не изменился." },
    ],
    defaultVisualization: { before: ["3", "1", "4"], after: ["1", "3", "4"], type: "list-transform" },
    applications: ["Сортировка без изменения данных", "Топ-N элементов", "Анализ данных"],
    sampleInput: "[9, 3, 6]",
    sampleOutput: "[3, 6, 9]",
  },
  {
    slug: "sum",
    name: "sum()",
    category: "Функциональные инструменты",
    shortDescription: "Суммирует все числа в итерируемом объекте.",
    fullDescription: "Функция sum() складывает все числовые элементы. Можно указать начальное значение.",
    defaultCode: "numbers = [1, 2, 3, 4]\nresult = sum(numbers)",
    defaultInput: "[1, 2, 3, 4]",
    defaultOutput: "10",
    defaultSteps: [
      { title: "Функция sum()", description: "Складываем все элементы." },
      { title: "Результат", description: "1 + 2 + 3 + 4 = 10." },
    ],
    defaultVisualization: { before: ["1", "2", "3", "4"], after: ["10"], type: "simple" },
    applications: ["Подсчёт итогов", "Статистика", "Финансовые расчёты"],
    sampleInput: "[5, 10, 15]",
    sampleOutput: "30",
  },
  {
    slug: "max",
    name: "max()",
    category: "Функциональные инструменты",
    shortDescription: "Возвращает наибольшее значение.",
    fullDescription: "Функция max() находит максимальный элемент в последовательности или среди аргументов.",
    defaultCode: "numbers = [3, 7, 2, 9]\nresult = max(numbers)",
    defaultInput: "[3, 7, 2, 9]",
    defaultOutput: "9",
    defaultSteps: [
      { title: "Функция max()", description: "Сравниваем все элементы." },
      { title: "Результат", description: "Наибольшее — 9." },
    ],
    defaultVisualization: { before: ["3", "7", "2", "9"], after: ["9"], type: "simple" },
    applications: ["Поиск рекорда", "Анализ данных", "Игровые очки"],
    sampleInput: "[1, 5, 3]",
    sampleOutput: "5",
  },
  {
    slug: "min",
    name: "min()",
    category: "Функциональные инструменты",
    shortDescription: "Возвращает наименьшее значение.",
    fullDescription: "Функция min() находит минимальный элемент в последовательности.",
    defaultCode: "numbers = [3, 7, 2, 9]\nresult = min(numbers)",
    defaultInput: "[3, 7, 2, 9]",
    defaultOutput: "2",
    defaultSteps: [
      { title: "Функция min()", description: "Сравниваем все элементы." },
      { title: "Результат", description: "Наименьшее — 2." },
    ],
    defaultVisualization: { before: ["3", "7", "2", "9"], after: ["2"], type: "simple" },
    applications: ["Поиск минимума", "Оптимизация", "Сравнение цен"],
    sampleInput: "[10, 4, 7]",
    sampleOutput: "4",
  },
  {
    slug: "dict-keys",
    name: "dict.keys()",
    category: "Словари",
    shortDescription: "Возвращает все ключи словаря.",
    fullDescription: "Метод keys() даёт представление всех ключей словаря. Можно преобразовать в список.",
    defaultCode: 'person = {"name": "Anna", "age": 16}\nresult = list(person.keys())',
    defaultInput: '{"name": "Anna", "age": 16}',
    defaultOutput: '["name", "age"]',
    defaultSteps: [
      { title: "Метод keys()", description: "Получаем все ключи словаря." },
      { title: "Результат", description: 'Ключи: "name", "age".' },
    ],
    defaultVisualization: { before: ["name", "age"], after: ["name", "age"], type: "dict-transform" },
    applications: ["Проверка полей", "Итерация по ключам", "Валидация JSON"],
    sampleInput: '{"a": 1, "b": 2}',
    sampleOutput: '["a", "b"]',
  },
  {
    slug: "dict-values",
    name: "dict.values()",
    category: "Словари",
    shortDescription: "Возвращает все значения словаря.",
    fullDescription: "Метод values() возвращает представление всех значений словаря.",
    defaultCode: 'person = {"name": "Anna", "age": 16}\nresult = list(person.values())',
    defaultInput: '{"name": "Anna", "age": 16}',
    defaultOutput: '["Anna", 16]',
    defaultSteps: [
      { title: "Метод values()", description: "Получаем все значения." },
      { title: "Результат", description: 'Значения: "Anna", 16.' },
    ],
    defaultVisualization: { before: ["name", "age"], after: ["Anna", "16"], type: "dict-transform" },
    applications: ["Анализ данных", "Подсчёт значений", "Экспорт данных"],
    sampleInput: '{"x": 10, "y": 20}',
    sampleOutput: "[10, 20]",
  },
  {
    slug: "dict-items",
    name: "dict.items()",
    category: "Словари",
    shortDescription: "Возвращает пары (ключ, значение).",
    fullDescription: "Метод items() возвращает представление пар ключ-значение. Удобен для перебора словаря.",
    defaultCode: 'data = {"a": 1, "b": 2}\nresult = list(data.items())',
    defaultInput: '{"a": 1, "b": 2}',
    defaultOutput: '[("a", 1), ("b", 2)]',
    defaultSteps: [
      { title: "Метод items()", description: "Получаем пары ключ-значение." },
      { title: "Результат", description: "Каждый элемент — кортеж из двух значений." },
    ],
    defaultVisualization: { before: ["a", "b"], after: ['("a", 1)', '("b", 2)'], type: "dict-transform" },
    applications: ["Перебор словаря", "Сериализация", "Преобразование в список"],
    sampleInput: '{"x": 5}',
    sampleOutput: '[("x", 5)]',
  },
  {
    slug: "dict-get",
    name: "dict.get()",
    category: "Словари",
    shortDescription: "Безопасно получает значение по ключу.",
    fullDescription: "Метод get(key, default) возвращает значение или default, если ключ не найден. Не вызывает ошибку.",
    defaultCode: 'student = {"name": "Ivan"}\nresult = student.get("grade")',
    defaultInput: '{"name": "Ivan"}',
    defaultOutput: "None",
    defaultSteps: [
      { title: "Метод get()", description: 'Ищем ключ "grade".' },
      { title: "Результат", description: "Ключ не найден → None." },
    ],
    defaultVisualization: { before: ["grade"], after: ["None"], type: "simple" },
    applications: ["Безопасный доступ к данным", "Конфигурации", "API-ответы"],
    sampleInput: '{"name": "Anna"}',
    sampleOutput: '"Anna"',
  },
  {
    slug: "range",
    name: "range()",
    category: "Циклы",
    shortDescription: "Создаёт последовательность чисел.",
    fullDescription: "Функция range(start, stop) генерирует числа от start до stop-1. Основа для циклов for.",
    defaultCode: "result = list(range(0, 5))",
    defaultInput: "range(0, 5)",
    defaultOutput: "[0, 1, 2, 3, 4]",
    defaultSteps: [
      { title: "Функция range()", description: "Создаём числа от 0 до 4." },
      { title: "Результат", description: "Список [0, 1, 2, 3, 4]." },
    ],
    defaultVisualization: { before: ["0..4"], after: ["0", "1", "2", "3", "4"], type: "list-transform" },
    applications: ["Циклы for", "Индексы", "Генерация последовательностей"],
    sampleInput: "range(1, 4)",
    sampleOutput: "[1, 2, 3]",
  },
  {
    slug: "enumerate",
    name: "enumerate()",
    category: "Циклы",
    shortDescription: "Добавляет индекс к каждому элементу.",
    fullDescription: "Функция enumerate() возвращает пары (индекс, элемент) при переборе списка.",
    defaultCode: 'fruits = ["apple", "banana"]\nresult = list(enumerate(fruits))',
    defaultInput: '["apple", "banana"]',
    defaultOutput: '[(0, "apple"), (1, "banana")]',
    defaultSteps: [
      { title: "Функция enumerate()", description: "Нумеруем элементы списка." },
      { title: "Результат", description: "Пары (0, apple), (1, banana)." },
    ],
    defaultVisualization: { before: ["apple", "banana"], after: ['(0, "apple")', '(1, "banana")'], type: "zip-pair" },
    applications: ["Нумерация списков", "Циклы с индексом", "Логирование"],
    sampleInput: '["a", "b", "c"]',
    sampleOutput: '[(0, "a"), (1, "b"), (2, "c")]',
  },
  {
    slug: "zip",
    name: "zip()",
    category: "Циклы",
    shortDescription: "Объединяет элементы нескольких списков попарно.",
    fullDescription: "Функция zip() создаёт итератор кортежей из элементов нескольких последовательностей.",
    defaultCode: 'names = ["Anna", "Ivan"]\nscores = [5, 4]\nresult = list(zip(names, scores))',
    defaultInput: '["Anna", "Ivan"] + [5, 4]',
    defaultOutput: '[("Anna", 5), ("Ivan", 4)]',
    defaultSteps: [
      { title: "Функция zip()", description: "Объединяем имена и оценки." },
      { title: "Результат", description: "Пары (Anna, 5), (Ivan, 4)." },
    ],
    defaultVisualization: { before: ["Anna", "Ivan", "➕", "5", "4"], after: ['("Anna", 5)', '("Ivan", 4)'], type: "zip-pair" },
    applications: ["Параллельный перебор", "Таблицы данных", "Объединение колонок"],
    sampleInput: "[1, 2] + [3, 4]",
    sampleOutput: "[(1, 3), (2, 4)]",
  },
  {
    slug: "map",
    name: "map()",
    category: "Функциональные инструменты",
    shortDescription: "Применяет функцию к каждому элементу.",
    fullDescription: "Функция map(func, iterable) возвращает итератор с результатами применения func к каждому элементу.",
    defaultCode: "numbers = [1, 2, 3]\nresult = list(map(lambda x: x * 2, numbers))",
    defaultInput: "[1, 2, 3]",
    defaultOutput: "[2, 4, 6]",
    defaultSteps: [
      { title: "Функция map()", description: "Умножаем каждый элемент на 2." },
      { title: "Результат", description: "[2, 4, 6]." },
    ],
    defaultVisualization: { before: ["1", "2", "3"], after: ["2", "4", "6"], type: "filter-map" },
    applications: ["Преобразование данных", "Массовые операции", "Функциональное программирование"],
    sampleInput: "[10, 20]",
    sampleOutput: "[20, 40]",
  },
  {
    slug: "filter",
    name: "filter()",
    category: "Функциональные инструменты",
    shortDescription: "Фильтрует элементы по условию.",
    fullDescription: "Функция filter(func, iterable) оставляет только элементы, для которых func возвращает True.",
    defaultCode: "numbers = [1, 2, 3, 4, 5]\nresult = list(filter(lambda x: x % 2 == 0, numbers))",
    defaultInput: "[1, 2, 3, 4, 5]",
    defaultOutput: "[2, 4]",
    defaultSteps: [
      { title: "Функция filter()", description: "Оставляем только чётные числа." },
      { title: "Результат", description: "[2, 4]." },
    ],
    defaultVisualization: { before: ["1", "2", "3", "4", "5"], after: ["2", "4"], type: "filter-map" },
    applications: ["Фильтрация данных", "Поиск по условию", "Очистка списков"],
    sampleInput: "[1, 2, 3]",
    sampleOutput: "[2]",
  },
  {
    slug: "lambda",
    name: "lambda",
    category: "Функциональные инструменты",
    shortDescription: "Создаёт анонимную функцию в одну строку.",
    fullDescription: "Lambda — короткий способ записать простую функцию без def. Синтаксис: lambda аргументы: выражение.",
    defaultCode: "add = lambda x, y: x + y\nresult = add(3, 5)",
    defaultInput: "3, 5",
    defaultOutput: "8",
    defaultSteps: [
      { title: "Lambda-функция", description: "Создаём функцию сложения." },
      { title: "Вызов", description: "add(3, 5) = 8." },
    ],
    defaultVisualization: { before: ["3", "5"], after: ["8"], type: "simple" },
    applications: ["sort с key", "map и filter", "Короткие callback-функции"],
    sampleInput: "2, 3",
    sampleOutput: "5",
  },
  {
    slug: "int",
    name: "int()",
    category: "Преобразование типов",
    shortDescription: "Преобразует значение в целое число.",
    fullDescription: "Функция int() конвертирует строку или число с плавающей точкой в целое.",
    defaultCode: 'text = "42"\nresult = int(text)',
    defaultInput: '"42"',
    defaultOutput: "42",
    defaultSteps: [
      { title: "Функция int()", description: 'Преобразуем строку "42".' },
      { title: "Результат", description: "Получаем число 42 типа int." },
    ],
    defaultVisualization: { before: ["42"], after: ["42"], type: "type-convert" },
    applications: ["Парсинг ввода", "Математика", "Индексы"],
    sampleInput: '"100"',
    sampleOutput: "100",
  },
  {
    slug: "str",
    name: "str()",
    category: "Преобразование типов",
    shortDescription: "Преобразует значение в строку.",
    fullDescription: "Функция str() создаёт строковое представление любого объекта.",
    defaultCode: "number = 42\nresult = str(number)",
    defaultInput: "42",
    defaultOutput: '"42"',
    defaultSteps: [
      { title: "Функция str()", description: "Преобразуем число в строку." },
      { title: "Результат", description: 'Получаем "42".' },
    ],
    defaultVisualization: { before: ["42"], after: ['"42"'], type: "type-convert" },
    applications: ["Конкатенация", "Форматирование вывода", "Логирование"],
    sampleInput: "123",
    sampleOutput: '"123"',
  },
  {
    slug: "float",
    name: "float()",
    category: "Преобразование типов",
    shortDescription: "Преобразует значение в дробное число.",
    fullDescription: "Функция float() конвертирует строку или целое число в число с плавающей точкой.",
    defaultCode: 'text = "3.14"\nresult = float(text)',
    defaultInput: '"3.14"',
    defaultOutput: "3.14",
    defaultSteps: [
      { title: "Функция float()", description: 'Преобразуем "3.14".' },
      { title: "Результат", description: "Получаем 3.14 типа float." },
    ],
    defaultVisualization: { before: ["3.14"], after: ["3.14"], type: "type-convert" },
    applications: ["Научные расчёты", "Финансы", "Физика"],
    sampleInput: '"2.5"',
    sampleOutput: "2.5",
  },
  {
    slug: "list",
    name: "list()",
    category: "Преобразование типов",
    shortDescription: "Создаёт список из итерируемого объекта.",
    fullDescription: "Функция list() преобразует строку, кортеж или другой итерируемый объект в список.",
    defaultCode: 'text = "abc"\nresult = list(text)',
    defaultInput: '"abc"',
    defaultOutput: '["a", "b", "c"]',
    defaultSteps: [
      { title: "Функция list()", description: "Разбиваем строку на символы." },
      { title: "Результат", description: '["a", "b", "c"].' },
    ],
    defaultVisualization: { before: ["abc"], after: ["a", "b", "c"], type: "string-split" },
    applications: ["Конвертация типов", "Работа с символами", "Копирование данных"],
    sampleInput: '"hi"',
    sampleOutput: '["h", "i"]',
  },
  {
    slug: "tuple",
    name: "tuple()",
    category: "Преобразование типов",
    shortDescription: "Создаёт неизменяемый кортеж.",
    fullDescription: "Функция tuple() создаёт кортеж — упорядоченную неизменяемую коллекцию.",
    defaultCode: 'items = ["a", "b", "c"]\nresult = tuple(items)',
    defaultInput: '["a", "b", "c"]',
    defaultOutput: '("a", "b", "c")',
    defaultSteps: [
      { title: "Функция tuple()", description: "Преобразуем список в кортеж." },
      { title: "Результат", description: "Кортеж нельзя изменить после создания." },
    ],
    defaultVisualization: { before: ["a", "b", "c"], after: ["(a)", "(b)", "(c)"], type: "list-transform" },
    applications: ["Координаты", "Ключи словаря", "Неизменяемые данные"],
    sampleInput: "[1, 2]",
    sampleOutput: "(1, 2)",
  },
  {
    slug: "set",
    name: "set()",
    category: "Преобразование типов",
    shortDescription: "Создаёт множество уникальных элементов.",
    fullDescription: "Функция set() удаляет дубликаты и создаёт неупорядоченное множество.",
    defaultCode: "numbers = [1, 2, 2, 3, 3, 3]\nresult = set(numbers)",
    defaultInput: "[1, 2, 2, 3, 3, 3]",
    defaultOutput: "{1, 2, 3}",
    defaultSteps: [
      { title: "Функция set()", description: "Удаляем повторяющиеся элементы." },
      { title: "Результат", description: "Остаются {1, 2, 3}." },
    ],
    defaultVisualization: { before: ["1", "2", "2", "3", "3"], after: ["1", "2", "3"], type: "list-transform" },
    applications: ["Уникальные значения", "Множества в математике", "Дедупликация"],
    sampleInput: "[5, 5, 6]",
    sampleOutput: "{5, 6}",
  },
];

export function getFunctionBySlug(slug: string): PythonFunction | undefined {
  return pythonFunctions.find((f) => f.slug === slug);
}

export function getAllSlugs(): string[] {
  return pythonFunctions.map((f) => f.slug);
}

function shuffleArray<T>(arr: T[]): T[] {
  const copy = [...arr];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}

export function generateTrainerQuestion(): TrainerQuestion {
  const fn = pickRandom(pythonFunctions);
  const example = generateExample(fn.slug);
  const correct = example.outputValue;

  const wrongCandidates = pythonFunctions
    .filter((f) => f.slug !== fn.slug)
    .map((f) => {
      try {
        return generateExample(f.slug).outputValue;
      } catch {
        return f.sampleOutput;
      }
    })
    .filter((v) => v !== correct);

  const wrong = shuffleArray([...new Set(wrongCandidates)]).slice(0, 3);
  while (wrong.length < 3) {
    wrong.push(`"${pickRandom(["error", "null", "undefined"])}"`);
  }

  const options = shuffleArray([correct, ...wrong.slice(0, 3)]);

  return {
    functionSlug: fn.slug,
    functionName: fn.name,
    code: example.code,
    correctAnswer: correct,
    options,
    explanation: example.steps.map((s) => s.description).join(" "),
  };
}

export function generateTrainerSession(count = 10): TrainerQuestion[] {
  return Array.from({ length: count }, () => generateTrainerQuestion());
}
